version: "3.3"
services:
  web:
    hostname: web_wbd_1
    image: tubes-wbd-1:latest
    env_file: .env
    ports:
      - 8008:80
    volumes:
      - ./src:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
  db:
    hostname: db_wbd_1
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
